### ISSUE TITLE
 Linux 依赖包都安装好了但是执行subfix create modelscope --source_dir origin --language ZH 直接报错？

### ISSUE THREAD

**Issue by TzyTman** [cronrpc/SubFix#11]

**Comment by TzyTman** [comment]
subfix create modelscope --source_dir origin --language ZH
Checkout command with args: Namespace(command='create', solution='modelscope', source_dir='origin', target_dir='dataset', cache_dir='cache', sample_rate=44100, language='ZH', output='demo.list', max_seconds=15, absolute_path='False', func=<function handle_create at 0x7fee5d4a5280>)
find ffmpeg installed, use ffmpeg
files count: 1
max_threads = 72
2024-01-31 07:00:04,389 - modelscope - INFO - PyTorch version 2.2.0 Found.
2024-01-31 07:00:04,390 - modelscope - INFO - Loading ast index from /home/mk/.cache/modelscope/ast_indexer
2024-01-31 07:00:04,423 - modelscope - INFO - No valid ast index found from /home/mk/.cache/modelscope/ast_indexer, generating ast index from prebuilt!
2024-01-31 07:00:04,473 - modelscope - INFO - Loading done! Current index file version is 1.11.1, with md5 656b8ca63dc275fd6287f2ed4f9e945f and a total number of 956 components indexed
2024-01-31 07:00:06,589 - modelscope - INFO - Use user-specified model revision: v1.2.4
2024-01-31 07:00:06,967 - modelscope - WARNING - ('PIPELINES', 'auto-speech-recognition', 'asr-inference') not found in ast index file
Traceback (most recent call last):
  File "/home/mk/anaconda3/envs/SubFix/bin/subfix", line 33, in <module>
    sys.exit(load_entry_point('SubFix', 'console_scripts', 'subfix')())
  File "/home/mk/SubFix-main/subfix/cli.py", line 120, in cli
    args.func(args)
  File "/home/mk/SubFix-main/subfix/cli.py", line 40, in handle_create
    run_task(args)
  File "/home/mk/SubFix-main/subfix/solution/modelscope_multi_lang.py", line 73, in run_task
    create_list(args.source_dir, args.target_dir, args.cache_dir, args.sample_rate, args.language, args.output, args.max_seconds, args.absolute_path)
  File "/home/mk/SubFix-main/subfix/solution/modelscope_multi_lang.py", line 55, in create_list
    asr_model = Speech_Paraformer_Large_Vad_Punc_Asr_zh()
  File "/home/mk/SubFix-main/subfix/models/audio/asr/speech_paraformer_large_vad_punc_asr_zh.py", line 9, in __init__
    self._inference_pipeline = pipeline(
  File "/home/mk/anaconda3/envs/SubFix/lib/python3.9/site-packages/modelscope/pipelines/builder.py", line 170, in pipeline
    return build_pipeline(cfg, task_name=task)
  File "/home/mk/anaconda3/envs/SubFix/lib/python3.9/site-packages/modelscope/pipelines/builder.py", line 65, in build_pipeline
    return build_from_cfg(
  File "/home/mk/anaconda3/envs/SubFix/lib/python3.9/site-packages/modelscope/utils/registry.py", line 198, in build_from_cfg
    raise KeyError(
KeyError: 'asr-inference is not in the pipelines registry group auto-speech-recognition. Please make sure the correct version of ModelScope library is used.'

**Comment by TzyTman** [comment]
我这边修改了依赖库的版本号：
funasr                    1.0.0
modelscope                1.11.0
在运行 subfix create modelscope --source_dir origin --language ZH
有报了新的错误：
Traceback (most recent call last):
  File "/home/mk/anaconda3/envs/SubFix/lib/python3.9/site-packages/modelscope/utils/registry.py", line 212, in build_from_cfg
    return obj_cls(**args)
  File "/home/mk/anaconda3/envs/SubFix/lib/python3.9/site-packages/modelscope/pipelines/audio/asr_inference_pipeline.py", line 122, in __init__
    self.cmd = self.get_cmd(kwargs, model)
  File "/home/mk/anaconda3/envs/SubFix/lib/python3.9/site-packages/modelscope/pipelines/audio/asr_inference_pipeline.py", line 376, in get_cmd
    self.load_vad_model(cmd)
  File "/home/mk/anaconda3/envs/SubFix/lib/python3.9/site-packages/modelscope/pipelines/audio/asr_inference_pipeline.py", line 421, in load_vad_model
    model_cfg['model']['model_config']['vad_model_name'])
KeyError: 'model_config'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mk/anaconda3/envs/SubFix/bin/subfix", line 33, in <module>
    sys.exit(load_entry_point('SubFix', 'console_scripts', 'subfix')())
  File "/home/mk/SubFix-main/subfix/cli.py", line 120, in cli
    args.func(args)
  File "/home/mk/SubFix-main/subfix/cli.py", line 40, in handle_create
    run_task(args)
  File "/home/mk/SubFix-main/subfix/solution/modelscope_multi_lang.py", line 73, in run_task
    create_list(args.source_dir, args.target_dir, args.cache_dir, args.sample_rate, args.language, args.output, args.max_seconds, args.absolute_path)
  File "/home/mk/SubFix-main/subfix/solution/modelscope_multi_lang.py", line 55, in create_list
    asr_model = Speech_Paraformer_Large_Vad_Punc_Asr_zh()
  File "/home/mk/SubFix-main/subfix/models/audio/asr/speech_paraformer_large_vad_punc_asr_zh.py", line 9, in __init__
    self._inference_pipeline = pipeline(
  File "/home/mk/anaconda3/envs/SubFix/lib/python3.9/site-packages/modelscope/pipelines/builder.py", line 170, in pipeline
    return build_pipeline(cfg, task_name=task)
  File "/home/mk/anaconda3/envs/SubFix/lib/python3.9/site-packages/modelscope/pipelines/builder.py", line 65, in build_pipeline
    return build_from_cfg(
  File "/home/mk/anaconda3/envs/SubFix/lib/python3.9/site-packages/modelscope/utils/registry.py", line 215, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
KeyError: "AutomaticSpeechRecognitionPipeline: 'model_config'"

**Comment by TzyTman** [comment]
有那位大神知道怎么解决么？

**Comment by cronrpc** [comment]
由于modelscope的API发生了改动，所以之前的代码用到的API失效了。
这里建议是，先升级modelscope和funASR到最新版本。之后更新下SubFix就可以用了。
如果升级无效的话，可以直接用github仓库的版本。
```
# 安装FunASR
git clone https://github.com/alibaba/FunASR.git && cd FunASR
pip3 install -e ./

# 安装modelscope
git clone https://github.com/modelscope/modelscope.git
cd modelscope
pip install -e .
pip install -e .[audio]
```

现在用`subfix create modelscope --source_dir origin --language ZH`命令后得到的文本是没有标点符号的。
如果要用标点符号，使用下面的命令，自动将list文件进行标点。
```
subfix punctuation --load_list demo.list
```

**Comment by TzyTman** [comment]
按照你的方法还是报错。
Traceback (most recent call last):
  File "/home/mk/anaconda3/envs/SubFix/bin/subfix", line 33, in <module>
    sys.exit(load_entry_point('SubFix', 'console_scripts', 'subfix')())
  File "/home/mk/SubFix-main/subfix/cli.py", line 133, in cli
    args.func(args)
  File "/home/mk/SubFix-main/subfix/cli.py", line 47, in handle_create
    run_task(args)
  File "/home/mk/SubFix-main/subfix/solution/modelscope_multi_lang.py", line 73, in run_task
    create_list(args.source_dir, args.target_dir, args.cache_dir, args.sample_rate, args.language, args.output, args.max_seconds, args.absolute_path)
  File "/home/mk/SubFix-main/subfix/solution/modelscope_multi_lang.py", line 57, in create_list
    asr_model = Speech_UniASR_Asr_MultiLang(language=language, max_seconds=max_seconds)
  File "/home/mk/SubFix-main/subfix/models/audio/asr/speech_uniasr_asr_multilang.py", line 7, in __init__
    self.set_vad_model_by_language(language, max_seconds)
  File "/home/mk/SubFix-main/subfix/models/audio/asr/speech_uniasr_asr_multilang.py", line 38, in set_vad_model_by_language
    self._vad_model = Speech_Fsmn_Vad_Zh_16k_Common(max_seconds=max_seconds)
  File "/home/mk/SubFix-main/subfix/models/audio/vad/speech_fsmn_vad_zh.py", line 8, in __init__
    self._inference_pipeline = pipeline(
  File "/home/mk/anaconda3/envs/SubFix/lib/python3.9/site-packages/modelscope/pipelines/builder.py", line 170, in pipeline
    return build_pipeline(cfg, task_name=task)
  File "/home/mk/anaconda3/envs/SubFix/lib/python3.9/site-packages/modelscope/pipelines/builder.py", line 65, in build_pipeline
    return build_from_cfg(
  File "/home/mk/anaconda3/envs/SubFix/lib/python3.9/site-packages/modelscope/utils/registry.py", line 215, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: FunASRPipeline: GenericFunASR: 'NoneType' object is not callable

**Comment by TzyTman** [comment]
已解决 多谢大神！

**Comment by TzyTman** [comment]
已解决了啊！
